# Generated by Django 3.2.7 on 2021-12-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_controller', '0002_fix_gpio_pinoutputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='steppermotor',
            name='_init_delay',
            field=models.FloatField(default=0.01, help_text='Delay before first step (seconds)'),
        ),
        migrations.AddField(
            model_name='steppermotor',
            name='_step_delay',
            field=models.FloatField(default=0.01, help_text='Delay between steps (seconds)'),
        ),
    ]
