# Generated by Django 3.2.7 on 2022-01-06 15:04

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motor_controller', '0003_add_step_and_init_delay_to_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, common.models.Lockout),
        ),
        migrations.RemoveField(
            model_name='motor',
            name='name',
        ),
        migrations.AddField(
            model_name='steppermotor',
            name='_direction_of_rotation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='steppermotor',
            name='_steptype',
            field=models.CharField(default='Full', max_length=200, verbose_name='Full'),
            preserve_default=False,
        ),
    ]
